export const HANDLE_STEP_CHANGE = "HANDLE_STEP_CHANGE";
export const ADD_NEW_COMMENT = "ADD_NEW_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const HANDLE_INPUT_CHANGE = "HANDLE_INPUT_CHANGE";